-- Setting up a sample table


DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL CHECK(balance >= 0),
    PRIMARY KEY(id)
);


-- Begin a transaction

INSERT INTO accounts(name,balance)
VALUES('Bob',10000);



-- To start a transaction explicitly, you execute either one of the following statements:

BEGIN TRANSACTION;


-- or

BEGIN WORK;

-- or

BEGIN;



BEGIN;

INSERT INTO accounts(name,balance)
VALUES('Alice',10000);




-- From the current session, you can see the change by retrieving data from the accounts table:

SELECT
    id,
    name,
    balance
FROM
    accounts;



-- However, you will not see the change if you connect to the PostgreSQL server in a new session and execute the query above:

SELECT
    id,
    name,
    balance
FROM
    accounts;


-- Commit a transaction
-- To permanently apply the change to the database, you commit the transaction by using the COMMIT WORK statement:

COMMIT WORK;


-- or

COMMIT TRANSACTION;



-- or
COMMIT;



-- Other sessions can view the change by retrieving data from the accounts table:


SELECT
    id,
    name,
    balance
FROM
    accounts;



-- Roll back a transaction
-- If you want to undo the changes to the database, you can use the ROLLBACK statement:

ROLLBACK;
-- Or more clear:

ROLLBACK TRANSACTION;
-- Or:

ROLLBACK WORK;

