services:
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console UI
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      - minio-network
    restart: unless-stopped

networks:
  minio-network:
    driver: bridge
